export const adminMetrics = [
  {
    id: 'events',
    label: 'Total eventos',
    value: '124',
    delta: '+12% vs mes anterior',
    tone: 'gold',
    icon: 'calendar',
  },
  {
    id: 'tickets',
    label: 'Entradas vendidas',
    value: '8,432',
    delta: '+5.4% vs mes anterior',
    tone: 'violet',
    icon: 'ticket',
  },
  {
    id: 'occupancy',
    label: 'Ocupacion media',
    value: '87%',
    delta: '-2% vs mes anterior',
    tone: 'danger',
    icon: 'users',
  },
  {
    id: 'revenue',
    label: 'Recaudacion',
    value: '$420k',
    delta: '+18% vs mes anterior',
    tone: 'gold',
    icon: 'wallet',
  },
];

export const adminEvents = [
  {
    id: 1,
    title: 'Conferencia Tech Summit 2024',
    venue: 'Centro de Convenciones',
    date: '15 Oct, 2024',
    capacity: '5,000',
    sold: '4,850',
    fill: 97,
    status: 'Casi lleno',
    statusTone: 'warning',
    image: 'summit',
  },
  {
    id: 2,
    title: 'Festival de Musica Indie',
    venue: 'Parque Central',
    date: '22 Nov, 2024',
    capacity: '12,000',
    sold: '12,000',
    fill: 100,
    status: 'Agotado',
    statusTone: 'neutral',
    image: 'concert',
  },
  {
    id: 3,
    title: 'Taller de Fotografia Urbana',
    venue: 'Estudio Creativo Centro',
    date: '05 Dic, 2024',
    capacity: '50',
    sold: '12',
    fill: 24,
    status: 'Abierto',
    statusTone: 'success',
    image: 'workshop',
  },
];

export const adminCategories = ['Musica', 'Deportes', 'Teatro', 'Charlas', 'Cursos', 'E-Sports', 'Comedia'];
