export const categories = ['Todos', 'Musica', 'Deportes', 'Teatro', 'Charlas'];

export const events = [
  {
    slug: 'festival-primavera-sound',
    category: 'Musica',
    badge: 'DESTACADO',
    date: '15 Nov - 20:00 hs',
    fullDate: 'Sabado 15 de noviembre, 2026',
    timeRange: '20:00 - 02:00 hs',
    title: 'Festival Primavera Sound Buenos Aires',
    subtitle: 'Una noche inmersiva con artistas internacionales, visuales en vivo y una puesta premium al aire libre.',
    location: 'Parque Sarmiento, CABA',
    address: 'Av. Dr. Ricardo Balbin 4750, Ciudad Autonoma de Buenos Aires',
    priceLabel: 'DESDE',
    price: '$45.000',
    numericPrice: 45000,
    image: 'concert',
    capacity: '18.000 asistentes',
    mapLabel: 'Polo de eventos, zona norte',
    description: [
      'Primavera Sound Buenos Aires reune a artistas consagrados y nuevas promesas en una experiencia pensada para vivir la musica con produccion de primer nivel.',
      'El predio cuenta con food trucks, barras tematicas, zonas de descanso y una puesta de luces sincronizada con cada bloque del lineup.',
      'Ideal para grupos de amigos, parejas y quienes quieran vivir un festival grande sin salir de la ciudad.',
    ],
    tickets: [
      { name: 'General', price: 45000, description: 'Acceso al campo general y areas gastronomicas', available: true, note: 'Quedan pocas entradas' },
    ],
  },
  {
    slug: 'tech-summit-argentina',
    category: 'Charlas',
    date: '22 Nov - 09:00 hs',
    fullDate: 'Sabado 22 de noviembre, 2026',
    timeRange: '09:00 - 18:30 hs',
    title: 'Tech Summit Argentina 2024',
    subtitle: 'Conferencias, networking y paneles con referentes de producto, IA, datos y desarrollo.',
    location: 'Centro de Convenciones, CABA',
    address: 'Av. Figueroa Alcorta 2099, Ciudad Autonoma de Buenos Aires',
    priceLabel: 'DESDE',
    price: '$15.000',
    numericPrice: 15000,
    image: 'summit',
    capacity: '3.200 asistentes',
    mapLabel: 'Distrito de congresos y negocios',
    description: [
      'Tech Summit esta orientado a estudiantes, profesionales y equipos que quieran ponerse al dia con tendencias de tecnologia, producto e inteligencia artificial.',
      'La agenda incluye keynotes, workshops, espacios de networking y una feria de startups con demos en vivo durante toda la jornada.',
      'Es una gran opcion para conectar con reclutadores, founders y lideres tecnicos del ecosistema local.',
    ],
    tickets: [
      { name: 'Pase general', price: 15000, description: 'Acceso a todas las charlas y zona expo', available: true, note: 'Early bird extendido' },
    ],
  },
  {
    slug: 'hamlet-version-contemporanea',
    category: 'Teatro',
    badge: 'ULTIMAS',
    date: '05 Dic - 21:30 hs',
    fullDate: 'Viernes 5 de diciembre, 2026',
    timeRange: '21:30 - 23:45 hs',
    title: 'Hamlet: Una version contemporanea',
    subtitle: 'Una reinterpretacion intensa y visualmente impactante del clasico de Shakespeare.',
    location: 'Teatro San Martin, CABA',
    address: 'Av. Corrientes 1530, Ciudad Autonoma de Buenos Aires',
    priceLabel: 'DESDE',
    price: '$8.500',
    numericPrice: 8500,
    image: 'theater',
    capacity: '800 butacas',
    mapLabel: 'Circuito teatral del centro',
    description: [
      'Esta puesta de Hamlet combina escenografia minimalista, direccion contemporanea y un elenco con fuerte presencia escenica.',
      'La obra propone una lectura actual sobre poder, duelo y decision, con una banda sonora original y recursos multimedia en escena.',
      'Es ideal para quienes disfrutan del teatro clasico pero buscan una experiencia mas cercana y actual.',
    ],
    tickets: [
      { name: 'Platea general', price: 8500, description: 'Butaca numerada en platea central', available: true, note: 'Ultimas filas medias' },
    ],
  },
  {
    slug: 'final-copa-de-la-liga',
    category: 'Deportes',
    soldOut: true,
    date: '10 Dic - 17:00 hs',
    fullDate: 'Jueves 10 de diciembre, 2026',
    timeRange: '17:00 - 19:30 hs',
    title: 'Final Copa de la Liga',
    subtitle: 'La definicion del campeonato en un estadio lleno, con previa, show y clima de final.',
    location: 'Estadio Monumental, CABA',
    address: 'Av. Pres. Figueroa Alcorta 7597, Ciudad Autonoma de Buenos Aires',
    priceLabel: 'DESDE',
    price: '$25.000',
    numericPrice: 25000,
    image: 'stadium',
    capacity: '84.000 asistentes',
    mapLabel: 'Corredor deportivo de Nuñez',
    description: [
      'La final de la Copa de la Liga concentra a dos de los equipos mas fuertes del torneo en una noche de estadio repleto y maxima tension competitiva.',
      'El operativo de acceso incluye anillos de control, ingresos sectorizados y recomendaciones especiales de llegada para evitar demoras.',
      'Aunque las entradas estan agotadas, la ficha sirve para dejar lista la experiencia cuando haya una nueva fecha deportiva destacada.',
    ],
    tickets: [
      { name: 'Popular', price: 25000, description: 'Entrada agotada', available: false, note: 'Sin stock' },
    ],
  },
  {
    slug: 'noche-de-jazz-tributo-a-miles',
    category: 'Musica',
    date: '12 Dic - 22:00 hs',
    fullDate: 'Sabado 12 de diciembre, 2026',
    timeRange: '22:00 - 01:00 hs',
    title: 'Noche de Jazz: Tributo a Miles Davis',
    subtitle: 'Un set intimista con sexteto en vivo, cocteleria de autor y atmosfera de club nocturno.',
    location: 'Thelonious Club, CABA',
    address: 'Nicaragua 5549, Ciudad Autonoma de Buenos Aires',
    priceLabel: 'DESDE',
    price: '$5.000',
    numericPrice: 5000,
    image: 'jazz',
    capacity: '220 asistentes',
    mapLabel: 'Circuito cultural de Palermo',
    description: [
      'Una noche pensada para amantes del jazz y de los shows en venues chicos, con sonido cuidado y cercania total con los musicos.',
      'El repertorio recorre distintas etapas de Miles Davis, desde el hard bop hasta sus fases mas experimentales.',
      'La propuesta se completa con carta de tragos, gastronomia liviana y mesas compartidas.',
    ],
    tickets: [
      { name: 'Mesa general', price: 5000, description: 'Ingreso con ubicacion compartida', available: true, note: 'Incluye consumicion minima' },
    ],
  },
  {
    slug: 'workshop-react-principiantes',
    category: 'Cursos',
    badge: 'ABIERTA',
    date: '15 Dic - 10:00 hs',
    fullDate: 'Martes 15 de diciembre, 2026',
    timeRange: '10:00 - 13:30 hs',
    title: 'Workshop: React para Principiantes',
    subtitle: 'Clase guiada con proyecto practico, materiales y mentorias en vivo para arrancar desde cero.',
    location: 'Evento Online',
    address: 'Streaming en vivo por plataforma privada',
    priceLabel: 'PRECIO',
    price: 'Gratis',
    numericPrice: 0,
    image: 'workshop',
    capacity: '1.500 accesos online',
    mapLabel: 'Modalidad remota',
    description: [
      'Este workshop esta pensado para quienes quieren dar sus primeros pasos en React y entender componentes, estado, props y armado de interfaces.',
      'Incluye codigo base, ejercicios en vivo y una sesion final de preguntas para resolver dudas concretas del proyecto personal de cada participante.',
      'No hace falta experiencia previa mas alla de nociones basicas de HTML, CSS y JavaScript.',
    ],
    tickets: [
      { name: 'Acceso online', price: 0, description: 'Clase completa + material descargable', available: true, note: 'Inscripcion abierta' },
    ],
  },
  {
    slug: 'torneo-nacional-valorant',
    category: 'E-Sports',
    date: '18 Dic - 14:00 hs',
    fullDate: 'Viernes 18 de diciembre, 2026',
    timeRange: '14:00 - 22:00 hs',
    title: 'Torneo Nacional de Valorant',
    subtitle: 'Playoffs presenciales con equipos top, hosts en vivo y experiencias gamer en arena.',
    location: 'Arena Sur, CABA',
    address: 'Av. Saenz 459, Ciudad Autonoma de Buenos Aires',
    priceLabel: 'DESDE',
    price: '$3.000',
    numericPrice: 3000,
    image: 'esports',
    capacity: '4.500 asistentes',
    mapLabel: 'Hub de eventos competitivos',
    description: [
      'La fecha final del torneo nacional de Valorant ofrece escenario central, casteo en vivo y activaciones de marcas para la comunidad gamer.',
      'Habra meet and greet con creadores, zonas free play y espacios para sacar fotos con cosplayers y equipos participantes.',
      'Una buena opcion para ir con amigos y vivir un evento competitivo con produccion grande.',
    ],
    tickets: [
      { name: 'Entrada arena', price: 3000, description: 'Acceso a tribunas y zona fan', available: true, note: 'Stock normal' },
    ],
  },
  {
    slug: 'stand-up-especial-fin-de-ano',
    category: 'Comedia',
    date: '20 Dic - 23:00 hs',
    fullDate: 'Domingo 20 de diciembre, 2026',
    timeRange: '23:00 - 00:40 hs',
    title: 'Stand Up: Especial Fin de Ano',
    subtitle: 'Monologos filosos, invitados sorpresa y energia de cierre de temporada.',
    location: 'Paseo La Plaza, CABA',
    address: 'Av. Corrientes 1660, Ciudad Autonoma de Buenos Aires',
    priceLabel: 'DESDE',
    price: '$6.000',
    numericPrice: 6000,
    image: 'comedy',
    capacity: '420 asistentes',
    mapLabel: 'Polo de comedia del centro',
    description: [
      'Un especial de stand up con comediantes invitados, rutinas nuevas y un cierre pensado para despedir el ano con humor.',
      'La sala ofrece servicio de bar, ubicaciones por orden de llegada y buena visibilidad desde todos los sectores.',
      'Ideal para ir en grupo y cortar la semana con una salida relajada.',
    ],
    tickets: [
      { name: 'Entrada general', price: 6000, description: 'Acceso a platea libre', available: true, note: 'Ultimas tandas promocionales' },
    ],
  },
];

export const getEventBySlug = (slug) => events.find((event) => event.slug === slug);
